name: production
root: ~/
windows:
  - singletons:
      layout: even-vertical
      panes:
        - ssh rhiza@asgard-account.rhizalytics.com
        - ssh rhiza@54.159.188.219   # dwh
        - ssh rhiza@54.83.100.151  # etl
        - ssh rhiza@23.22.145.238  # proxy
        - ssh rhiza@54.147.214.122  # redis
        
  - application:
      layout: even-vertical
      panes:
       - ssh rhiza@54.162.147.53  #app
       - ssh rhiza@54.226.110.38  # app

  - jq:
      layout: even-vertical
      panes:
        - ssh rhiza@54.211.180.154  # worker
        - ssh rhiza@54.204.145.29  # worker
        - ssh rhiza@54.162.82.203  # worker
        - ssh rhiza@184.73.99.188  # worker
        - ssh rhiza@54.80.185.190  # worker
